DEFAULT_FOLDER = lily58/rev1
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes   
AUTOCORRECT_ENABLE = yes
LEADER_ENABLE = yes

# with cat 
##DEFAULT_FOLDER = lily58/rev1
#OLED_ENABLE = yes
#MOUSEKEY_ENABLE = yes   
# AUTOCORRECT_ENABLE = yes
# LEADER_ENABLE = yes
#OLED_ENABLE = yes
#WPM_ENABLE = yes
#SLEEP_LED_ENABLE = no   
